#include <assert.h>
#include <stdlib.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <sys/time.h>
#include "mem.h"

#define MILLISECONDS_PER_SECOND 1000
#define MICROSECONDS_PER_MILLISECOND 1000 

static struct timeval start_time; 
static struct timeval finish_time; 

// Finds the time in milliseconds elapsed between time2 and time1
static unsigned int get_difference_in_time(struct timeval* time1, struct timeval* time2){
  return (time1->tv_sec - time2->tv_sec)*MILLISECONDS_PER_SECOND + (time1->tv_usec - time2->tv_usec)/MICROSECONDS_PER_MILLISECOND;
}

int main(int argc, char* argv[]) {

  gettimeofday(&start_time, NULL); 

  if (argc != 4) {
    printf("Usage: %s sd # 0/1\nsd is a seed used for srand()\n# specifies the number of tests\n0/1 specifies False/True for enabling comparison with malloc\n", argv[0]);
    exit(0);
  }

  // psudeo-random seed
  unsigned int seed = atoi(argv[1]);
  
  // number of operations to perform
  long long n = atoll(argv[2]);

  // if true, write data into allocated memory
  bool writeData = atoi(argv[3]);

  // maximum number of concurrent allocations to track
  int max_allocs = 1000;

  // size for allocation request
  int min_alloc_size = 1;
  int max_alloc_size = 128;
  
  // allowed constant overhead
  int slack = 32;

  // max header size per allocation
  int header_size = 32;

  // request size up to 64+32, header up to 32 bytes
  int max_chunk_size = max_alloc_size + header_size;

  // most possible space, no more than max_allocs+1 unusable free chunks
  int region_size = max_allocs * max_chunk_size * 2 + max_chunk_size;

  void** ptr = calloc(sizeof(void*), max_allocs);
  int* size = calloc(sizeof(int), max_allocs);
  void** shadow = calloc(sizeof(void*), max_allocs);

  /*******************************************************************
   Please note that random() gives psudeo-random, not true random data.
   If the seed is set to the same value, the sequence generated by
   random() will be the same. Using psuedo-random number generators is
   a common testing technique.
  *******************************************************************/
  srandom(seed);

  //assert(Mem_Init(region_size + slack) == 0);

  int slot;
  bool doAlloc;
  //bool doWrite;

  long long i;


  for (i=0; i<n; i++) {
    slot = random() % max_allocs;
    doAlloc = random() % 4;
    //doWrite = writeData;

    if (!doAlloc || ptr[slot] != NULL) {
      //assert(Mem_Free(ptr[slot], 1) == 0);
      (free(ptr[slot]));
      free(shadow[slot]);
      ptr[slot] = NULL;
      shadow[slot] = NULL;
    }

    if (doAlloc) {
      size[slot] = min_alloc_size +
	(random() % (max_alloc_size - min_alloc_size + 1));
      ptr[slot] = malloc(size[slot]);
      if(!ptr[slot]){
	printf("m_error: %d\n", m_error);
      }
      assert(ptr[slot] != NULL);
      if (writeData) {
	shadow[slot] = malloc(size[slot]);
	int j;
	for (j=0; j<size[slot]; j++) {
	  char data = random();
	  *((char*)(ptr[slot] + j)) = data;
	  *((char*)(shadow[slot] + j)) = data;
	}
      }
    }
  }
  
  if (writeData) {
    for (slot=0; slot<max_allocs; slot++) {
      if (ptr[slot] != NULL) {
	assert(memcmp(ptr[slot], shadow[slot], size[slot]) == 0);
      }
    }
  }

  gettimeofday(&finish_time, NULL); 
  printf("%d\n", get_difference_in_time(&finish_time, &start_time)); 
  
  exit(0);
}

